# 应用名称
spring:
  application:
    name: es_demo
  data:
    elasticsearch:
      repositories:
        enabled: true
      client:
        reactive:
          endpoints: http://192.168.142.131:9200/

# 应用端口
server:
  port: 80


